### ISSUE TITLE
Create release tag

### ISSUE THREAD

**Issue by Bukashk0zzz** [fazland/FazlandElasticaBundle#11]
For now I get "Version of dependencies should be fixed" issue from https://insight.sensiolabs.com/what-we-analyse/composer.unfixed_dependency_version in my project.

Please make release tag for current version.

**Comment by giovannialbero1992** [comment]
Hi @Bukashk0zzz ! For the moment we are waiting to release a tagged version because it's incomplete yet.

**Comment by enumag** [comment]
@giovannialbero1992 Any news?

**Comment by giovannialbero1992** [comment]
@enumag for the moment we are waiting news by FosElastica's contributor, we have accepted to become collaborator on FosElasticaBundle although we are evaluating to return on our bundle because the developing of bundle is very slow for our needs

**Comment by enumag** [comment]
@giovannialbero1992 I have some more questions:

1) Have you decided if you will collaborate on FosElastica or stick with this fork?
2) What are the differences between the two bundles at the moment? In the readme you have "This bundle is started from FosElasticaBundle but it works with ElasticSearch 2.* ." - is FosElastica still incompatible with ElasticSearch 2?
3) Any plans about [ruflin/elastica v5.0](https://github.com/ruflin/Elastica/releases/tag/5.0.0)?

**Comment by giovannialbero1992** [comment]
@enumag 
1. Is almost sure that we'll come back on our bundle
2. For the moment FosElasticaBundle:master is compatible with ElasticSearch  2.*
3. There is a PR on FosElasticaBundle made by @alekitto (https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1171) that brings compatibility with ES5, probably we'll take that PR on our bundle

**Comment by giovannialbero1992** [comment]
@Bukashk0zzz @enumag 
# release 4.0 is available :) [link](https://github.com/fazland/FazlandElasticaBundle/releases/tag/4.0.0)
