### ISSUE TITLE
Hierarchical data

### ISSUE THREAD

**Issue by Mislop** [fazland/FazlandElasticaBundle#13]
Hello,

I use symfony, where is doc for option "_parent" ??

**Comment by alekitto** [comment]
The usage of the `_parent` field in this bundle is documented here: https://github.com/fazland/FazlandElasticaBundle/blob/master/Resources/doc/types.md#parent-fields

Please refer to the official ES documentation for more information on how the parent-child relationship works in ElasticSearch

**Comment by Mislop** [comment]
If i need to get parent in the same entity? For exemple if i have Category1 in my entity Category and Category2 in my entity Category and i need to get Category1 (Parent) and Category2 (child) ? This is my problem

**Comment by alekitto** [comment]
Sorry, can't understand your problem. Can't you just map the parent from the child entity via its property (specifying the same type in the `_parent` mapping)?

**Comment by Mislop** [comment]
For example : 

I have entity book, in this entity i have association with category. In my entity category i can get parent with method. In my mapping (config.yml) i have this :

book:
mappings:
name: ~
bookCategory: { type: 'object', properties: { id : {type: 'integer'}, name: {type: 'string', index: 'not_analyzed'}, parent: {type: 'object', properties: {name: {type: 'string', index: 'not_analyzed'}, parent: {type: 'object', properties: {name: {type: 'string', index: 'not_analyzed'}}}}} } }
persistence:
driver: 'orm'
model: 'AppBundle\Entity\Book\Book'
provider:
batch_size: 5000
listener: ~
finder: ~

I get my categories but separately.

category : [key,count]
subCategory: [key, count]
subsubCategory: [key, count]

i need this :

category : [key, count, subCategory [ key, count, subsubCategory [ key, count]]]

Thanks,

**Comment by Mislop** [comment]
My aggregation : 

public static $AGGREGATIONS : [
'term' =>
            'category' => 'accessoryCategory.parent.parent.name',
            'subCategory' => 'accessoryCategory.parent.name',
            'subsubCategory' => 'accessoryCategory.name'
        ]
];

**Comment by alekitto** [comment]
What you need can't be done in elasticsearch with parent-child relationship.
With your mapping, to get 
`category : [key, count, subCategory [ key, count, subsubCategory [ key, count]]]`
you just need nested aggregations

**Comment by Mislop** [comment]
My mapping is good? 
My problem is just my aggregations ?
What is path to get this ? : 

'category : [key, count, subCategory [ key, count, subsubCategory [ key, count]]]' ?

In public static $AGGREGATIONS : [
'term' =>
'category' => 'accessoryCategory.parent.parent.name',
'subCategory' => 'accessoryCategory.parent.name',
'subsubCategory' => 'accessoryCategory.name'
]
];

How subCategory know it is in 'category' ? 

(Sorry for my bad english)

What is path in nested aggregation? 
And whats is function addParam? The documentation does not explain

**Comment by alekitto** [comment]
Excuse me, but this is not a support forum for elasticsearch.
Please refer to the official documentation on how to model your mapping and how to use aggregations, or post a question on StackOverflow, ES dedicated Google groups or other support forum.
