### ISSUE TITLE
Index Manager Update API

### ISSUE THREAD

**Issue by The-Don-Himself** [fazland/FazlandElasticaBundle#14]
Hi,

Really loving the new features and up-to date dependencies over FOSElastica.

I'm wondering if there is or could be an easy way to insert, update and delete documents. For example, if we were to borrow from the easy API used in FOSHttpCacheBundle for cache invalidates and refresh

http://foshttpcachebundle.readthedocs.io/en/latest/features/invalidation.html#cache-manager

Ours could be for example

$indexManager = $container->get('fazlandelastica.index_manager');

$index = $indexManager->getIndex('app');
$type = $index->getType('users');

// Update a user id
$type->updateId('1');

// Bulk Update user ids
$type->bulkUpdateIds('1,2,3,4,5');

// Or if we already have the objects to avoid re-querying

// Update a user object
$type->updateObject($user);

// Bulk Update user objects
$type->bulkUpdateObjects($users);

Or does this functionality already exist? I went through the docs and code but couldn't find such a method.

**Comment by alekitto** [comment]
You can use the object persister services (ex `$container->get('fazland_elastica.object_persister.type.name')`) calling `replaceOne` or `replaceMany` methods passing an object or an array of objects.
Probably we should document this better

**Comment by The-Don-Himself** [comment]
Thanks @alekitto
Will look into this as soon as I'm back to my dev machine

Quick question though, will this service pass objects directly to Elastica or will it inherit the model_to_elastica transformers?

**Comment by alekitto** [comment]
It uses the object transformer
