### ISSUE TITLE
Incompatible declaration in Fazland\ElasticaBundle\Elastica\Client:16

### ISSUE THREAD

**Issue by ZloyPotroh** [fazland/FazlandElasticaBundle#19]
php7.0.18
symfony 2.8
fazland/elastica-bundle: dev-master
ruflin/elastica: dev-master

After commit:
https://github.com/ruflin/Elastica/commit/3e3a1affd1b8097ed942ae2364c454ae6872e201
getting warning:

ContextErrorException in Client.php line 16:
Warning: Declaration of Fazland\ElasticaBundle\Elastica\Client::request($path, $method = Elastica\Request::GET, $data = Array, array $query = Array) should be compatible with Elastica\Client::request($path, $method = Elastica\Request::GET, $data = Array, array $query = Array, $contentType = Elastica\Request::DEFAULT_CONTENT_TYPE)

**Comment by alekitto** [comment]
Has been fixed in https://github.com/fazland/FazlandElasticaBundle/commit/795e188afb0cc1f006505bb5ebea246307166450 which added the `$contentType` optional argument to the method signature.
Are you sure you are using the `dev-master` version of elastica-bundle?

**Comment by ZloyPotroh** [comment]
Yep. i'm using 'dev-master', and update has been called after this commit. But maybe smthng went wrong. Now all is ok after one more update. Thanks.
